[package]
name = "test_ffi"
version = "0.1.0"
authors = ["Matthew Gregan <kinetik@flim.org>"]
edition = "2018"

[dependencies]
mp4parse_capi = { path = "../mp4parse_capi" }

[build-dependencies]
cbindgen = "0.14.2"
mp4parse_capi = { path = "../mp4parse_capi" }
cc = "1.0"
